USE dogshotel;
INSERT INTO cage(description, free, occupied, price) VALUES ('Duży kojec 1', true, false, 39);
INSERT INTO cage(description, free, occupied, price) VALUES ('Duży kojec 2', true, false, 39);
INSERT INTO cage(description, free, occupied, price) VALUES ('Duży kojec 3', true, false, 39);
INSERT INTO cage(description, free, occupied, price) VALUES ('Duży kojec 4', true, false, 39);
INSERT INTO cage(description, free, occupied, price) VALUES ('Duży kojec 5', true, false, 39);
INSERT INTO cage(description, free, occupied, price) VALUES ('Duży kojec 6', true, false, 39);
INSERT INTO cage(description, free, occupied, price) VALUES ('Duży kojec 7', true, false, 39);
INSERT INTO cage(description, free, occupied, price) VALUES ('Mały kojec 1', true, false, 25);
INSERT INTO cage(description, free, occupied, price) VALUES ('Mały kojec 2', true, false, 25);
INSERT INTO cage(description, free, occupied, price) VALUES ('Mały kojec 3', true, false, 25);
INSERT INTO cage(description, free, occupied, price) VALUES ('Mały kojec 4', true, false, 25);
INSERT INTO cage(description, free, occupied, price) VALUES ('Mały kojec 5', true, false, 25);
INSERT INTO cage(description, free, occupied, price) VALUES ('Mały kojec 6', true, false, 25);
INSERT INTO cage(description, free, occupied, price) VALUES ('Mały kojec 7', true, false, 25);
INSERT INTO cage(description, free, occupied, price) VALUES ('Mały kojec 8', true, false, 25);
INSERT INTO cage(description, free, occupied, price) VALUES ('Pokój w budynku 1', true, false, 35);
INSERT INTO cage(description, free, occupied, price) VALUES ('Pokój w budynku 2', true, false, 35);
INSERT INTO cage(description, free, occupied, price) VALUES ('Pokój w budynku 3', true, false, 35);
INSERT INTO cage(description, free, occupied, price) VALUES ('Pokój w budynku 4', true, false, 35);
INSERT INTO cage(description, free, occupied, price) VALUES ('Pokój w budynku 5', true, false, 35);
INSERT INTO cage(description, free, occupied, price) VALUES ('Pokój w budynku 6', true, false, 35);
INSERT INTO cage(description, free, occupied, price) VALUES ('Pokój w budynku 7', true, false, 35);
INSERT INTO cage(description, free, occupied, price) VALUES ('Pokój w budynku 8', true, false, 35);
INSERT INTO cage(description, free, occupied, price) VALUES ('Dom 1', true, false, 50);
INSERT INTO cage(description, free, occupied, price) VALUES ('Dom 2', true, false, 50);
INSERT INTO cage(description, free, occupied, price) VALUES ('Dom 3', true, false, 50);
